// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`



declare namespace Cloudflare {
    interface Env {
        CORS_ORIGIN: ["http://localhost","http://localhost:3000","http://localhost:3002","https://patterns.github.io"];
        DB: D1Database;
    }
}
interface Env extends Cloudflare.Env {}
